spring.application.name=ImageHosting
#MySQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.format_sql=false

#Redis
spring.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.redis.password=${SPRING_DATA_REDIS_PASSWORD:}
spring.session.store-type=redis

#  A W S
# S3
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
cloud.aws.region.static=ap-south-1
cloud.aws.stack.auto =false
app.s3.bucket=upload-download-learn


# File Upload Configuration
app.s3.allowed.extensions=.pdf,.jpg,.jpeg,.png,.gif,.txt,.doc,.docx,.xls,.xlsx,.zip,.no-extension
app.s3.max.file.size=3145728
app.s3.max.download.in.memory=5242880

# Multipart Upload Configuration
app.s3.multipart.threshold=1
app.s3.thread.pool.size=5

# Server Configuration
server.port=8080
spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=3MB
spring.servlet.multipart.enabled=true

# Frontend URL (used for OAuth2 redirects and CORS)
app.frontend.url=${FRONTEND_URL}

# Elasticsearch Configuration
spring.elasticsearch.uris=${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}
spring.elasticsearch.connection-timeout=10s
spring.elasticsearch.socket-timeout=30s

# Optional: If using authentication
spring.elasticsearch.username=${ES_USERNAME:}
spring.elasticsearch.password=${ES_PASSWORD:}
spring.data.elasticsearch.repositories.enabled=true

# OAuth2 Client Registration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
